# Generated by Django 2.0.3 on 2018-12-04 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trans_sys', '0002_auto_20181202_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Semester',
        ),
        migrations.AddField(
            model_name='course',
            name='Semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trans_sys.Semester'),
            preserve_default=False,
        ),
    ]
