# Generated by Django 2.0.3 on 2018-11-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans_sys', '0002_student_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Hour',
            field=models.IntegerField(blank=True, null=True, verbose_name='Course Hour'),
        ),
    ]
