# Generated by Django 2.0.3 on 2018-12-04 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans_sys', '0003_auto_20181203_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Citizenship',
        ),
    ]
