# Generated by Django 2.0.3 on 2018-11-19 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trans_sys', '0003_auto_20181118_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trans_sys.Semester'),
            preserve_default=False,
        ),
    ]
